/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios.Principal;

//import Formularios.Huespedes.FrmPruebaHabitacion;
import Miselaneos.jFrameProyecto;
import Paneles.CambiaPanel;
import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.io.File;


/**
 *
 * @author nejo
 */
public class FrmPrincipal extends jFrameProyecto {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.btnHome.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new Paneles.pnlHome());
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/logoPrincipal.png")).getImage());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new Miselaneos.pnlSys();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlAbajo = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnHabitacion = new javax.swing.JButton();
        btnHuesped = new javax.swing.JButton();
        btnPersonal = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnCaja = new javax.swing.JButton();
        pnlTitulo1 = new Miselaneos.pnlSys();
        reloj1 = new Miselaneos.Reloj();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROYECTO HOTEL \"POCHITA\"");
        setBackground(new java.awt.Color(255, 0, 0));
        setMinimumSize(new java.awt.Dimension(1024, 600));
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlTitulo.setBackground(new java.awt.Color(255, 102, 0));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("                HOTEL \"POCHITA\" v1.0 ");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jLabel3.setRequestFocusEnabled(false);
        pnlTitulo.add(jLabel3, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlTitulo.add(jButton1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlAbajo.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlAbajo.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(255, 102, 0));
        pnlBotones.setMinimumSize(new java.awt.Dimension(326, 30));
        pnlBotones.setPreferredSize(new java.awt.Dimension(780, 40));

        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        btnHome.setText("Home");
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.setPreferredSize(new java.awt.Dimension(84, 64));
        btnHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });
        pnlBotones.add(btnHome);

        btnHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarHabitacion.png"))); // NOI18N
        btnHabitacion.setText("Habitación");
        btnHabitacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHabitacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHabitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHabitacionMouseClicked(evt);
            }
        });
        pnlBotones.add(btnHabitacion);

        btnHuesped.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huesped.png"))); // NOI18N
        btnHuesped.setText("Huesped");
        btnHuesped.setToolTipText("");
        btnHuesped.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuesped.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnHuesped.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHuespedMouseClicked(evt);
            }
        });
        pnlBotones.add(btnHuesped);

        btnPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personal.png"))); // NOI18N
        btnPersonal.setText("Personal");
        btnPersonal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPersonal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPersonalMouseClicked(evt);
            }
        });
        pnlBotones.add(btnPersonal);

        btnReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reservas.png"))); // NOI18N
        btnReservas.setText("Reservas");
        btnReservas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReservas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReservasMouseClicked(evt);
            }
        });
        pnlBotones.add(btnReservas);

        btnCaja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjeta.png"))); // NOI18N
        btnCaja.setText("Caja");
        btnCaja.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCaja.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCaja.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCajaMouseClicked(evt);
            }
        });
        pnlBotones.add(btnCaja);

        pnlAbajo.add(pnlBotones, java.awt.BorderLayout.CENTER);

        pnlTitulo1.setBackground(new java.awt.Color(255, 102, 0));
        pnlTitulo1.setPreferredSize(new java.awt.Dimension(180, 25));
        pnlTitulo1.setLayout(new java.awt.BorderLayout());

        reloj1.setForeground(new java.awt.Color(255, 255, 255));
        reloj1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reloj1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlTitulo1.add(reloj1, java.awt.BorderLayout.CENTER);

        pnlAbajo.add(pnlTitulo1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlAbajo, java.awt.BorderLayout.SOUTH);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (JOptionPane.showConfirmDialog(pnlPrincipal, "¿Desea cerrar el sistema?", "Atención wachin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlHome());
        
    }//GEN-LAST:event_btnHomeMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnHabitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHabitacionMouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlHabitacion());
    }//GEN-LAST:event_btnHabitacionMouseClicked

    private void btnHuespedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHuespedMouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlHuesped());
    }//GEN-LAST:event_btnHuespedMouseClicked

    private void btnPersonalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPersonalMouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlPersonal());
    }//GEN-LAST:event_btnPersonalMouseClicked

    private void btnReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReservasMouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlReservas());
        //JOptionPane.showMessageDialog(pnlPrincipal, "¡PROXIMAMENTE!", "¡Atención!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnReservasMouseClicked

    private void btnCajaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCajaMouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlReservas());
        //JOptionPane.showMessageDialog(pnlPrincipal, "¡PROXIMAMENTE!", "¡Atención!", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnCajaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaja;
    private javax.swing.JButton btnHabitacion;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnHuesped;
    private javax.swing.JButton btnPersonal;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlAbajo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlPrincipal;
    private Miselaneos.pnlSys pnlTitulo;
    private Miselaneos.pnlSys pnlTitulo1;
    private Miselaneos.Reloj reloj1;
    // End of variables declaration//GEN-END:variables
}
