/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp1_nuñez_2022;

import java.util.Scanner;

/**
 *
 * @author emi
 * 
 */
public class framePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form framePrincipal
     */
    public framePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Ejer1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Century Schoolbook L", 2, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Presione en el menú de arriba, \npara acceder a cada uno de los ejercicios.");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setBackground(new java.awt.Color(180, 10, 120));
        jLabel1.setFont(new java.awt.Font("MathJax_Typewriter", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(180, 10, 120));
        jLabel1.setText("Ejercicios trabajo practico N 1");

        Ejer1.setBackground(new java.awt.Color(180, 10, 120));
        Ejer1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        Ejer1.setText("Ejercicios del 1 al 8");

        jMenuItem2.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem2.setText("Ejercicio N1");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem2);

        jMenuItem3.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem3.setText("Ejercicio N2");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem3);

        jMenuItem14.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem14.setText("Ejercicio N3");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem14);

        jMenuItem15.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem15.setText("Ejercicio N4");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem15);

        jMenuItem16.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem16.setText("Ejercicio N5");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem16);

        jMenuItem17.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem17.setText("Ejercicio N6");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem17);

        jMenuItem18.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem18.setText("Ejercicio N7");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem18);

        jMenuItem19.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem19.setText("Ejercicio N8");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        Ejer1.add(jMenuItem19);

        jMenuBar1.add(Ejer1);

        jMenu2.setBackground(new java.awt.Color(180, 10, 120));
        jMenu2.setText("Ejercicios del 9 al 16");

        jMenuItem4.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem4.setText("Ejercicio N9");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem5.setText("Ejercicio N10");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem6.setText("Ejercicio N11");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem10.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem10.setText("Ejercicio N12");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem8.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem8.setText("Ejercicio N13");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem11.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem11.setText("Ejercicio N14");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem12.setText("Ejercicio N15");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem13.setText("Ejercicio N16");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuBar1.add(jMenu2);

        jMenu4.setBackground(new java.awt.Color(180, 10, 120));
        jMenu4.setText("Ejercicios del 17 al 24");

        jMenuItem20.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem20.setText("Ejercicio N17");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuItem21.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem21.setText("Ejercicio N18");
        jMenuItem21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem21ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem21);

        jMenuItem22.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem22.setText("Ejercicio N19");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem22);

        jMenuItem24.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem24.setText("Ejercicio N20");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem24);

        jMenuItem25.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem25.setText("Ejercicio N21");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem25);

        jMenuItem26.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem26.setText("Ejercicio N22");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem26);

        jMenuItem27.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem27.setText("Ejercicio N23");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem27);

        jMenuItem29.setForeground(new java.awt.Color(180, 10, 120));
        jMenuItem29.setText("Ejercicio N24");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem29);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        /*EJERCICIO 10: Dado dos números de tipo double donde a vale 7.8542, y b vale 4.2148, obtener el
resultado de la division en c. Posteriormente imprimir el resultado de c por consola.*/
        double a, b, c;
        a = 7.8542;
        b = 4.2148;
        c = a / b;
        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        /*EJERCICIO 12: Dadas 3 palabras, p1=Programa, p2=en, p3=Java, emitir por consola, Programa en Java.*/
        
        
        String p1 = "Programa";
        String p2 = "en";
        String p3 = "Java";
        
        System.out.println(""+ p1 +" "+ p2 +" "+ p3);
        System.exit(0);
        
        
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        /*EJERCICIO 15: Dados dos números enteros a=10 y b=5, determinar si el valor es mayor 15. Emitir por
consola el mensaje.*/
        int a, b;
        a = 10;
        b = 5;
        
        if(a>15){
            System.out.println("La variable a es mayor a 15");       
        }
        else{
            System.out.println("La variable a no es mayor a 15");
        }
        
        if(b>15){
            System.out.println("La variable b es mayor a 15");       
        }
        else{
            System.out.println("La variable b no es mayor a 15");
        }
        System.exit(0);        
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        /*EJERCICIO 2: Dado dos números enteros a y b, obtener el resultado de la resta en c. Posteriormente
emitir el resultado de c por consola.-*/
        Scanner sc = new Scanner(System.in);
        int a, b, c;

        System.out.println("Ingrese un numero: ");

       a = sc.nextInt();

        System.out.println("Ingrese otro numero: ");

        b = sc.nextInt();
        
         c = a - b;

        System.out.println("El resultado es: " + c);
        System.exit(0);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        /*EJERCICIO 5: Dado dos números enteros a y b, obtener el resultado de la residuo en c. Posteriormente
emitir el resultado de c por consola.*/
        Scanner sc = new Scanner(System.in);
        int a, b, c;

        System.out.println("Ingrese un numero: ");

       a = sc.nextInt();

        System.out.println("Ingrese otro numero: ");

        b = sc.nextInt();
        
        c = a % b;

        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        /*EJERCICIO 19: Definir un arraglo(array) de String para registrar los días de la semana. Suponiendo que
hoy es JUEVES, emitir un mensaje por consola “Hoy Es Jueves”. Tener en cuenta que el día de la
semana debe estar definida en una variable de tipo String y la evaluación de dicha variable se
debe hacer por medio de la estructura de control switch.*/
    String[] arr;
    arr = new String[7];

    arr[0] = "lunes";
    arr[1] = "martes"; 
    arr[2] = "miercoles";
    arr[3] = "jueves";
    arr[4] = "viernes";
    arr[5] = "sabado";
    arr[6] = "domingo";
    
    String dia = "jueves";
    
    switch (dia){
        case "lunes":
            System.out.println("Hoy es "+arr[0]);
            break;
        case "martes":
            System.out.println("Hoy es "+arr[1]);
            break;
        case "miercoles":
            System.out.println("Hoy es "+arr[2]);
            break;
        case "jueves":
            System.out.println("Hoy es "+arr[3]);
            break;
        case "viernes":
            System.out.println("Hoy es "+arr[4]);
            break;
        case "sabado":
            System.out.println("Hoy es "+arr[5]);
            break;
        case "domingo":
            System.out.println("Hoy es "+arr[6]);
            break;
        default:
            System.out.println("Dia inválido");
            break;
        
    }
    System.exit(0);

    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       /*EJERCICIO 1: Dado dos números enteros a y b, obtener el resultado de la suma en c. Posteriormente
emitir el resultado de c por consola. */
        
        
        Scanner sc = new Scanner(System.in);
        int a, b, c;

        System.out.println("Ingrese un numero: ");

       a = sc.nextInt();

        System.out.println("Ingrese otro numero: ");

        b = sc.nextInt();
        
        c = a + b;

        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        /*EJERCICIO 3: Dado dos números enteros a y b, obtener el resultado de la multiplicación en c.
Posteriormente emitir el resultado de c por consola.*/
        Scanner sc = new Scanner(System.in);
        int a, b, c;

        System.out.println("Ingrese un numero: ");

        a = sc.nextInt();

        System.out.println("Ingrese otro numero: ");

        b = sc.nextInt();
        
        c = a * b;

        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        /*EJERCICIO 4: Dado dos números enteros a y b, obtener el resultado de la división en c. Posteriormente
emitir el resultado de c por consola.*/
        Scanner sc = new Scanner(System.in);
        int a, b, c;

        System.out.println("Ingrese un numero: ");

       a = sc.nextInt();

        System.out.println("Ingrese otro numero: ");

        b = sc.nextInt();
        
        c = a / b;

        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        /*EJERCICIO 6: Dado un número entero a=5, incrementar su valor en 5, luego emitir su valor por consola.
Notar que no se hace mención a otro nombre de variable.*/
        int a = 5;
        System.out.println("Variable a: " + a);
        a = a + 5;
        System.out.println("Variable a: " + a);
        System.exit(0);        
        
        
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
        /*EJERCICIO 7: Dado dos números de tipo double donde a vale 7.8542, y b vale 4.2148, obtener el
resultado de la suma en c. Posteriormente imprimir el resultado de c por consola.*/
        double a, b, c;
        a = 7.8542;
        b = 4.2148;
        c = a + b;
        System.out.println("El resultado es: " + c);
        System.exit(0);
             
        
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        /*EJERCICIO 8: Dado dos números de tipo double donde a vale 7.8542, y b vale 4.2148, obtener el
resultado de la resta en c. Posteriormente emitir el resultado de c por consola.*/
        double a, b, c;
        a = 7.8542;
        b = 4.2148;
        c = a - b;
        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        /*EJERCICIO 9: Dado dos números de tipo double donde a vale 7.8542, y b vale 4.2148, obtener el
resultado de la multiplicación en c. Posteriormente emitir el resultado de c por consola.*/
        double a, b, c;
        a = 7.8542;
        b = 4.2148;
        c = a * b;
        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        /*EJERCICIO 11: Dado dos números de tipo double donde a vale 7.8542, y b vale 4.2148, obtener el
resultado del residuo en c. Posteriormente imprimir el resultado de c por consola.*/
        double a, b, c;
        a = 7.8542;
        b = 4.2148;
        c = a % b;
        System.out.println("El resultado es: " + c);
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        /*EJERCICIO 13: Usando le valor char ('\n') y 2 palabras, p1=Hola, p2=Mundo, lograr una salida por consola:
Hola
Mundo*/
        String p1 = "Hola";
        String p2 = "Mundo";
        System.out.println(""+ p1 + "\n" + p2);
        System.exit(0);       
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        /*EJERCICIO 14: Dados dos números enteros a=10 y b=5, determinar si el valor es igual 15. Emitir por
consola el mensaje.*/
        int a,b;
        a = 10;
        b = 5;
            
        switch (a){
            case 15:
                System.out.println("La variable a es igual a 15");
                break;
            default: 
                System.out.println("La variable a no es igual a 15");
                break;
        }        
        switch(b) {
            case 15:     
                System.out.println("La variable b es igual a 15");
                break;
            default:
                System.out.println("La variable b no es igual a 15");
                break;
        
        }  
        System.exit(0);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        /*EJERCICIO 16: Dados dos números enteros a=10 y b=5, determinar si el valor es menor a 15. Emitir por
consola el mensaje.*/
        int a, b;
        a = 10;
        b = 5;
        
        if(a<15){
            System.out.println("La variable a es menor que 15");       
        }
        else{
            System.out.println("La variable a no es menor que 15");
        }
        
        if(b<15){
            System.out.println("La variable b es menor que 15");       
        }
        else{
            System.out.println("La variable b no es menor que 15");
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        /* EJERCICIO 17: Definir un arraglo(array) de enteros de 3 posiciones, ingresar en la primer posición el valor
5, en la segunda posición, el valor 10 y en la tercer posición el valor 5. Por último emitir por
consola la suma y multiplicación de todas las posiciones.*/
    int[] arr;// declara un array de enteros.
    arr = new int[3];// asigna memoria para 3 enteros.
    arr[0] = 5;
    arr[1] = 10;
    arr[2] = 5;
    int suma = 0;
    int multiplicacion = 1;
    for (int i = 0; i < arr.length; i++){
        suma += arr[i];
        multiplicacion *= arr[i];
    }
            
    System.out.println("La suma de las posiciones del array es: " + suma);
    System.out.println("La multiplicacion de las posiciones del array es: "+ multiplicacion);
    System.exit(0);
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    private void jMenuItem21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem21ActionPerformed
        /*EJERCICIO 18: Definir un arreglo(array) de String de 2 posiciones, ingresar en la primer posición el valor
Hola, en la segunda posición, el valor Mundo. Por último emitir por consola la suma de la posición
2 y 1, en ese orden.*/
    String[] arr;
    arr = new String[2];

    arr[0] = "Hola";
    arr[1] = "Mundo"; 
    System.out.println(""+arr[1]+" "+arr[0]);
    System.exit(0);
    }//GEN-LAST:event_jMenuItem21ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        /*EJERCICIO 20: Definir un arraglo(array) de enteros de 10 posiciones, ingresar valores en cada
posición(valor del indice o puntero), por medio de un bucle (while) y posteriormente emitir por
consola por medio de un bucle (for).*/
        
      int arr[]=new int[10];
      
      int contador = 0;
      while(contador < 10 ){
          arr[contador]=contador;
          contador++;
        }
      for (int i = 0; i < arr.length; i++){
          System.out.println(""+arr[i]);
        }
              
    System.exit(0);
        
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        /*EJERCICIO 21: Definir un arraglo(array) de enteros de 10 posiciones, ingresar valores, donde el primer
valor es 1, por medio de un bucle (while) y posteriormente emitir por consola por medio de un
bucle (for). Tener en cuanta en el bucle (for) si el valor de la posición de array es 8, debe salir del
recorrido del bucle.*/
      int arr[]=new int[10];
      
      int contador = 0;
      while(contador < 10 ){
          arr[contador]=contador+1;
          contador++;
        }
      for (int i = 0; i < arr.length; i++){
          if (i==8){
            break;
          }else{
            System.out.println(""+arr[i]);
          }
        }
              
    System.exit(0);
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        /*EJERCICIO 22: Definir un arraglo(array) de enteros de 10 posiciones, ingresar valores, donde el primer
valor es 1, por medio de un bucle (while) y posteriormente emitir por consola por medio de un
bucle (for). Tener en cuenta en el bucle (for) si el valor de la posición de array es 8, continuar a la
posición 9 y seguir con el bucle.*/
    int arr[]=new int[10];
      
    int contador = 0;
    while(contador < 10 ){
          arr[contador]=contador+1;
          contador++;
        }
    for (int i = 0; i < arr.length; i++){
        if (i==8){
           continue;
        }else{
            System.out.println(""+arr[i]);
          }
        }
              
    System.exit(0);
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        /*EJERCICIO 23: Definir una clase calendario, que tenga un método para evaluar si una cadena de String
que se le pase pueda decir si es verdad o no que es un día de la semana. Similar al Ejercicio 19.*/
        
        Calendario c1 = new Calendario();
        String dia = "jueves";
        if(c1.diaSemana(dia)){
            System.out.println("Es un dia de la semana");
        }else{
            System.out.println("No es un dia de la semana");
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        /*EJERCICIO 24: Definir una clase calculadora, la misma tiene que poder sumar, restar, dividir y multiplicar
dos números enteros y 2 numero de tipo double, también debe tener un método que se pide en el
Ejercicio 20. El valor resultante de cada método, debe poder emitirse por consola.*/
       
        Calculadora c2 = new Calculadora();
        int a = 22;
        int b = 4;
        double c = 10.14;
        double d = 2.12;
        System.out.println("El resultado de la suma de enteros es: "+c2.sumaEntero(a, b));
        System.out.println("El resultado de la resta de enteros es: "+c2.restaEntero(a, b));
        System.out.println("El resultado de la multiplicación de enteros es: "+c2.multiEntero(a, b));
        System.out.println("El resultado de la división de enteros es: "+c2.divisionEntero(a, b)+"\n");
        System.out.println("El resultado de la suma de decimales es: "+c2.sumaDecimal(c, d));
        System.out.println("El resultado de la resta de decimales es: "+c2.restaDecimal(c, d));
        System.out.println("El resultado de la multiplicación de decimales es: "+c2.multiDecimal(c, d));
        System.out.println("El resultado de la división de decimales es: "+c2.divisionDecimal(c, d));

        System.exit(0);
    }//GEN-LAST:event_jMenuItem29ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(framePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new framePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Ejer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
