/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial1_nuñez_2022;

import java.util.ArrayList;

/**
 *
 * @author emi
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Ejercicio 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ejercicio 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ejercicio 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Parcial N° 1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(20, 20, 20)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel1)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //EJERCICIO 3
        //se crea la colección heterogenea
        ArrayList<Empleado> empleados = new ArrayList<>();
        
        //se agregan los vendedores, repartidores, administrativos, gerentes e ingenieros, se le asignas los respectivos salarios y porcentajes.
        Vendedor vend1 = new Vendedor(4d,19000.0d);
        vend1.setNombre("Gian Grancic");
        empleados.add(vend1);
        
        Repartidor re1 = new Repartidor(5d,20000.0d);
        re1.setNombre("Facundo Alvarez");
        empleados.add(re1);
        
        Repartidor re2 = new Repartidor(5d,20000.0d);
        re2.setNombre("Nicolas Acevedo");
        empleados.add(re2);
        
        Ingeniero ing1 = new Ingeniero(7d,28000.0d);
        ing1.setNombre("Ezequiel Ferreyra");
        empleados.add(ing1);
        
        Gerente ger1 = new Gerente(10d,41000.0d);
        ger1.setNombre("Daniel Urban");
        empleados.add(ger1);
        
        Gerente ger2 = new Gerente(10d,41000.0d);
        ger2.setNombre("Jorge Nuñez");
        empleados.add(ger2);
        
        Administrativo ad1 = new Administrativo(8d,25000.0d);
        ad1.setNombre("Emilia Nuñez");
        empleados.add(ad1);
        
        Administrativo ad2 = new Administrativo(8d,25000.0d);
        ad2.setNombre("Daiana Gonzalez");
        empleados.add(ad2);
      
      //se crean variable de tipo contador para acumular los salarios y aguinaldos de cada empleado. 
      double totalSalarios = 0;
      double totalAguinaldos = 0;
      double totalGerentes = 0;
        
      //en el for se pregunta si es instancia de Empleado, para asi poder acceder al método de cada subclase.
      for (int i = 0; i < empleados.size(); i++) {
          Empleado e = empleados.get(i);
          if(e instanceof Gerente){
            Gerente g = (Gerente)e;
            double aguinaldo = g.calcularAguinaldo();
            //en esta variable se acumulan los aguinaldos.
            totalAguinaldos += aguinaldo;
            //en esta variable se acumulan los sueldos y aguinaldos de los gerentes.
            totalGerentes += aguinaldo + g.getSalario();
            //en esta variable se acumulan el total de los salarios y aguinaldos.
            totalSalarios += g.getSalario() + aguinaldo;
         
          }else if(e instanceof Administrativo){
            Administrativo a = (Administrativo)e;
            double aguinaldo = a.calcularAguinaldo();
            totalAguinaldos += aguinaldo;
            totalSalarios += a.getSalario() + aguinaldo;
            
          }else if(e instanceof Repartidor){
            Repartidor r = (Repartidor)e;
            double aguinaldo = r.calcularAguinaldo();
            totalAguinaldos += aguinaldo;
            totalSalarios += r.getSalario() + aguinaldo;
            
          }else if(e instanceof Vendedor){
            Vendedor v = (Vendedor)e;
            double aguinaldo = v.calcularAguinaldo();
            totalAguinaldos += aguinaldo;
            totalSalarios += v.getSalario() + aguinaldo;
            
          }else{
            Ingeniero in = (Ingeniero)e;
            double aguinaldo = in.calcularAguinaldo();
            totalAguinaldos += aguinaldo;
            totalSalarios += in.getSalario() + aguinaldo;
            
              
          }
         
        }
      //se imprime por pantalla los datos requeridos por el dueño.
        System.out.println("El total a pagar de Aguinaldos es: "+totalAguinaldos);
        System.out.println("El total a pagar de Salarios y Aguinaldos es: "+totalSalarios);
        System.out.println("El total a pagar de Salarios y Aguinaldo a los Gerentes es: "+totalGerentes);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // EJERCICIO 2
        ArrayList<Habitacion> habitaciones = new ArrayList<Habitacion>();
        //se agrega la habitacion N°1.
        Habitacion h1 = new Habitacion();
        h1.setNro(1);
        h1.setPrecio(800.00d);
        
        Producto p1 = new Producto();
        p1.setNombre("Gaseosa");
        p1.setPrecio(250.00d);
        p1.setCantidad(2);
       
        Producto p2 = new Producto();
        p2.setNombre("snack");
        p2.setPrecio(180.00d);
        p2.setCantidad(3);
        
        Servicio s1 = new Servicio();
        s1.setNombre("TV");
        s1.setPrecio(200.00d);
        
        
        h1.getProductos().add(p1);
        h1.getProductos().add(p2);
        h1.getServicios().add(s1);
        
        habitaciones.add(h1);
        
        //se agrega la habitacion N°2.
        Habitacion h2 = new Habitacion();
        h2.setNro(2);
        h2.setPrecio(900.00d);
        
        Producto p3 = new Producto();
        p3.setNombre("Gaseosa");
        p3.setPrecio(250.00d);
        p3.setCantidad(1);
        
        Servicio s2 = new Servicio();
        s2.setNombre("TV");
        s2.setPrecio(200.00d);
        
        Servicio s3 = new Servicio();
        s3.setNombre("WIFI");
        s3.setPrecio(100.00d);
        
        
        h2.getProductos().add(p3);
        h2.getServicios().add(s2);
        h2.getServicios().add(s3);
        
        habitaciones.add(h2);
        
        //se agrega la habitacion N°3.
        Habitacion h3 = new Habitacion();
        h3.setNro(3);
        h3.setPrecio(700.00d);
        
        Servicio s4 = new Servicio();
        s4.setNombre("Aire Acondicionado");
        s4.setPrecio(150.00d);
        
        h3.getServicios().add(s4);
        
        habitaciones.add(h3);
        
        //se agrega la habitacion N°4.
        Habitacion h4 = new Habitacion();
        h4.setNro(4);
        h4.setPrecio(1000.00d);
        
        Producto p4 = new Producto();
        p4.setNombre("Gaseosa");
        p4.setPrecio(250.00d);
        p4.setCantidad(4);
       
        Producto p5 = new Producto();
        p5.setNombre("snack");
        p5.setPrecio(180.00d);
        p5.setCantidad(2);
        
        Servicio s5 = new Servicio();
        s5.setNombre("TV");
        s5.setPrecio(200.00d);
        
        Servicio s6 = new Servicio();
        s6.setNombre("WIFI");
        s6.setPrecio(100.00d);
        
        h4.getProductos().add(p4);
        h4.getProductos().add(p5);
        h4.getServicios().add(s5);
        h4.getServicios().add(s6);
        
        habitaciones.add(h4);
        
        //se agrega la habitación N°5.
        Habitacion h5 = new Habitacion();
        h5.setNro(1);
        h5.setPrecio(800.00d);
        
        Producto p6 = new Producto();
        p6.setNombre("Gaseosa");
        p6.setPrecio(250.00d);
        p6.setCantidad(1);
       
        Producto p7 = new Producto();
        p7.setNombre("snack");
        p7.setPrecio(180.00d);
        p7.setCantidad(1);
        
        Servicio s7 = new Servicio();
        s7.setNombre("WIFI");
        s7.setPrecio(100.00d);
        
        
        h5.getProductos().add(p6);
        h5.getProductos().add(p7);
        h5.getServicios().add(s7);
        
        habitaciones.add(h5);
        
        
        double totalProd = 0;
        double totalServ = 0;
        double resultado;
        //se recorre con el for las habitaciones para acceder a los productos, se ejecuta el metodo para calcular precio por cantidad.
        for(int i=0;i<habitaciones.size();i++){
            Habitacion h = habitaciones.get(i);
            for(int in=0;in<h.getProductos().size();in++){
                Producto prod = h.getProductos().get(in);
                resultado = prod.calcularProductos();
                totalProd += resultado;
            }
            h.setTotalProductos(totalProd);
            totalProd = 0;
        }
        //se recorre con el for para acceder a los servicios.
        for(int i=0;i<habitaciones.size();i++){
            Habitacion h = habitaciones.get(i);
            for(int in=0;in<h.getServicios().size();in++){
                Servicio serv = h.getServicios().get(in);
                double result = serv.getPrecio();
                totalServ += result;
            }
            h.setTotalServicios(totalServ);
            totalServ = 0;
        }
        double precioHabitacion=0.0d;
        double precioGeneral=0.0d;
        //se recorre por último con este for para imprimir los precios de productos, servicios y por habitacion.
        for (int i=0;i<habitaciones.size();i++){
            Habitacion h = habitaciones.get(i);
            precioHabitacion = h.getPrecio();
            precioHabitacion += h.getTotalProductos();
            precioHabitacion += h.getTotalServicios();
            precioGeneral+= precioHabitacion;
            System.out.println("El monto total de Servicios de la habitacion N°"+h.getNro()+" es de: $"+h.getTotalServicios());
            System.out.println("El monto total de Consumo en minibar de la habitacion N°"+h.getNro()+" es de: $"+h.getTotalProductos());
            System.out.println("El precio total de la habitación N° "+h.getNro()+" es de: $"+precioHabitacion+"\n");
            
        }
        //se imprime el monto total.
        System.out.println("El monto total general de consumo es de: $"+precioGeneral);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
