/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios.Principal;

//import Formularios.Huespedes.FrmPruebaHabitacion;
import Miselaneos.jFrameProyecto;
import Paneles.CambiaPanel;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author nejo
 */
public class FrmPrincipal extends jFrameProyecto {

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(this);
        this.jButton7.setSelected(true);
        
        new CambiaPanel(pnlPrincipal, new Paneles.pnlHome());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new Miselaneos.pnlSys();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlAbajo = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        pnlTitulo1 = new Miselaneos.pnlSys();
        reloj2 = new Miselaneos.Reloj();
        pnlPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("");
        setMinimumSize(new java.awt.Dimension(1, 1));
        getContentPane().setLayout(new java.awt.BorderLayout());

        pnlTitulo.setBackground(new java.awt.Color(255, 102, 0));
        pnlTitulo.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(255, 102, 0));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("                HOTEL \"POCHITA\" v1.0 ");
        jLabel3.setPreferredSize(new java.awt.Dimension(138, 40));
        jLabel3.setRequestFocusEnabled(false);
        pnlTitulo.add(jLabel3, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        pnlTitulo.add(jButton1, java.awt.BorderLayout.LINE_END);

        getContentPane().add(pnlTitulo, java.awt.BorderLayout.PAGE_START);

        pnlAbajo.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlAbajo.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(255, 102, 0));
        pnlBotones.setMinimumSize(new java.awt.Dimension(326, 30));
        pnlBotones.setPreferredSize(new java.awt.Dimension(780, 40));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/casa.png"))); // NOI18N
        jButton7.setText("Home");
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setPreferredSize(new java.awt.Dimension(91, 59));
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });
        pnlBotones.add(jButton7);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/agregarHabitacion.png"))); // NOI18N
        jButton8.setText("Habitación");
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotones.add(jButton8);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/huesped.png"))); // NOI18N
        jButton9.setText("Huesped");
        jButton9.setToolTipText("");
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotones.add(jButton9);

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/personal.png"))); // NOI18N
        jButton10.setText("Personal");
        jButton10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton10.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotones.add(jButton10);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reservas.png"))); // NOI18N
        jButton11.setText("Reservas");
        jButton11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton11.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotones.add(jButton11);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tarjeta.png"))); // NOI18N
        jButton12.setText("Caja");
        jButton12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton12.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnlBotones.add(jButton12);

        pnlAbajo.add(pnlBotones, java.awt.BorderLayout.CENTER);

        pnlTitulo1.setBackground(new java.awt.Color(255, 102, 0));
        pnlTitulo1.setPreferredSize(new java.awt.Dimension(180, 25));
        pnlTitulo1.setLayout(new java.awt.BorderLayout());

        reloj2.setBackground(new java.awt.Color(255, 102, 0));
        reloj2.setForeground(new java.awt.Color(255, 255, 255));
        reloj2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reloj2.setFont(new java.awt.Font("Liberation Sans", 1, 13)); // NOI18N
        pnlTitulo1.add(reloj2, java.awt.BorderLayout.CENTER);

        pnlAbajo.add(pnlTitulo1, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlAbajo, java.awt.BorderLayout.SOUTH);

        pnlPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnlPrincipal.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlPrincipal, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        if (JOptionPane.showConfirmDialog(pnlPrincipal, "¿Desea cerrar el sistema?", "Atención wachin", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        new CambiaPanel(pnlPrincipal, new Paneles.pnlHome());
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlAbajo;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlPrincipal;
    private Miselaneos.pnlSys pnlTitulo;
    private Miselaneos.pnlSys pnlTitulo1;
    private Miselaneos.Reloj reloj2;
    // End of variables declaration//GEN-END:variables
}
