/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tp4_nuñez_2022;

import java.util.ArrayList;


/**
 *
 * @author emi
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(0, 255, 255));
        jButton1.setForeground(new java.awt.Color(255, 0, 153));
        jButton1.setText("Ejercicio 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jButton1)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
       ArrayList<Cliente> listClientes = new ArrayList<Cliente>();

        Cliente c1 = new Cliente();
        c1.setNombre("Juan");
        c1.setEdad(29);
        c1.setSexo("M");
        c1.setIsEmbarazada(false);
        c1.setNroOrden(0);
        listClientes.add(c1);

        Cliente c2 = new Cliente();
        c2.setNombre("Silvia");
        c2.setEdad(35);
        c2.setSexo("F");
        c2.setIsEmbarazada(true);
        c2.setNroOrden(0);
        listClientes.add(c2);

        Cliente c3 = new Cliente();
        c3.setNombre("Gian");
        c3.setEdad(65);
        c3.setSexo("M");
        c3.setIsEmbarazada(false);
        c3.setNroOrden(0);
        listClientes.add(c3);

        Cliente c4 = new Cliente();
        c4.setNombre("Paula");
        c4.setEdad(30);
        c4.setSexo("F");
        c4.setIsEmbarazada(true);
        c4.setNroOrden(0);
        listClientes.add(c4);

        Cliente c5 = new Cliente();
        c5.setNombre("Jorge");
        c5.setEdad(46);
        c5.setSexo("M");
        c5.setIsEmbarazada(false);
        c5.setNroOrden(0);
        listClientes.add(c5);

        Cliente c6 = new Cliente();
        c6.setNombre("Ana");
        c6.setEdad(26);
        c6.setSexo("F");
        c6.setIsEmbarazada(false);
        c6.setNroOrden(0);
        listClientes.add(c6);

        Cliente c7 = new Cliente();
        c7.setNombre("Belen");
        c7.setEdad(66);
        c7.setSexo("F");
        c7.setIsEmbarazada(false);
        c7.setNroOrden(0);
        listClientes.add(c7);

        Cliente c8 = new Cliente();
        c8.setNombre("Ezequiel");
        c8.setEdad(38);
        c8.setSexo("M");
        c8.setIsEmbarazada(false);
        c8.setNroOrden(0);
        listClientes.add(c8);

        Cliente c9 = new Cliente();
        c9.setNombre("Alex");
        c9.setEdad(46);
        c9.setSexo("M");
        c9.setIsEmbarazada(false);
        c9.setNroOrden(0);
        listClientes.add(c9);

        Cliente c10 = new Cliente();
        c10.setNombre("Abril");
        c10.setEdad(70);
        c10.setSexo("F");
        c10.setIsEmbarazada(false);
        c10.setNroOrden(0);
        listClientes.add(c10);
        
       
        ArrayList<Cliente> clientesOrden  = new ArrayList<Cliente>();
        //busca las personas que esten embarazadas y las agrega a la lista ordenada.
        int Orden = 1;
        for (int i = 0; i < listClientes.size(); i++) {
            Cliente c = listClientes.get(i);
            String nom = c.getNombre();
            boolean emb = c.getIsEmbarazada();
            if (emb == true) {
                c.setNroOrden(Orden);
                Orden += 1;
                clientesOrden.add(c);}
        }
        //busca las personas que sean mayores de 64 años y las agrega acontinuación de la lista ordenada.
        for (int i = 0; i < listClientes.size(); i++) {
            Cliente c = listClientes.get(i);
            String nom = c.getNombre();
            int age = c.getEdad();
            if (age > 64) {
                c.setNroOrden(Orden);
                Orden += 1;
                clientesOrden.add(c);
            }
        }
        //busca las personas que no cumplan con las condiciones y las agrega a lo ultimo de la lista ordenada
        for (int i = 0; i < listClientes.size(); i++) {
            Cliente c = listClientes.get(i);
            String nom = c.getNombre();
            int age = c.getEdad();
            boolean emb = c.getIsEmbarazada();
            if (age < 65 && emb == false) {
               c.setNroOrden(Orden);
                Orden += 1;
                clientesOrden.add(c);
            }
        }
        //muestra los datos cargados en la lista ordenada.
        for (int i = 0; i < clientesOrden.size(); i++) {
            Cliente c = clientesOrden.get(i);
            System.out.println("Número de Orden: "+ c.getNroOrden() + " Nombre: "+ c.getNombre());
        
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
