/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package parcial2_nuñez_2022;

import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import static parcial2_nuñez_2022.Frame.isAlpha;
import static parcial2_nuñez_2022.Frame.isEmail;

/**
 *
 * @author emi
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
     
    DefaultTableModel modelo = null;
    TableRowSorter<TableModel> elQueOrdena = null;
    
    public Frame() {
        initComponents();
        modelo = (DefaultTableModel) jTable1.getModel();
        elQueOrdena = new TableRowSorter<TableModel>(modelo);
        jTable1.setModel(modelo);
        jTable1.setRowSorter(elQueOrdena);
    }
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    
    public static boolean isAlpha(String s) {
        return s != null && s.matches("^[a-zA-Z\\s]*$");
    }
    
    
    public static boolean isEmail(String e) {
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                        + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(e);
        return e != null && mather.find();
    }
    
    private void Clean(){
        surnameText.setText("");
        nameText.setText("");
        idText.setText("");
        homeText.setText("");
        locationText.setText("");
        neighborhoodText.setText("");
        phoneText.setText("");
        movil1Text.setText("");
        movil2Text.setText("");
        email1Text.setText("");
        email2Text.setText("");
        commentText.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idGroup1 = new javax.swing.ButtonGroup();
        id2 = new javax.swing.ButtonGroup();
        maritalGroup2 = new javax.swing.ButtonGroup();
        marital2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filterText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        nameText = new javax.swing.JTextField();
        surnameText = new javax.swing.JTextField();
        homeText = new javax.swing.JTextField();
        dni = new javax.swing.JRadioButton();
        Lc = new javax.swing.JRadioButton();
        Le = new javax.swing.JRadioButton();
        Ci = new javax.swing.JRadioButton();
        idText = new javax.swing.JTextField();
        email1Text = new javax.swing.JTextField();
        commentText = new javax.swing.JTextField();
        movil2Text = new javax.swing.JTextField();
        email2Text = new javax.swing.JTextField();
        movil1Text = new javax.swing.JTextField();
        locationText = new javax.swing.JTextField();
        phoneText = new javax.swing.JTextField();
        neighborhoodText = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        soltero = new javax.swing.JRadioButton();
        casado = new javax.swing.JRadioButton();
        nacimiento = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        nameText1 = new javax.swing.JTextField();
        surnameText1 = new javax.swing.JTextField();
        homeText1 = new javax.swing.JTextField();
        dniRadioButton1 = new javax.swing.JRadioButton();
        lcRadioButton1 = new javax.swing.JRadioButton();
        leRadioButton1 = new javax.swing.JRadioButton();
        ciRadioButton1 = new javax.swing.JRadioButton();
        idText1 = new javax.swing.JTextField();
        email1Text1 = new javax.swing.JTextField();
        commentText1 = new javax.swing.JTextField();
        movil2Text1 = new javax.swing.JTextField();
        email2Text1 = new javax.swing.JTextField();
        movil1Text1 = new javax.swing.JTextField();
        locationText1 = new javax.swing.JTextField();
        dateBirthText1 = new javax.swing.JTextField();
        phoneText1 = new javax.swing.JTextField();
        neighborhoodText1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        bussinesNameText = new javax.swing.JTextField();
        ageText = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));
        jPanel1.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(500, 500));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Tipo de Documento", "Documento", "Domicilio", "Localidad", "Barrio", "Fecha de Nac", "Teléfono", "Celular 1", "Celular 2", "Email 1", "Email 2", "Horario de Disponibilidad", "Estado Civil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setPreferredSize(new java.awt.Dimension(500, 500));
        jScrollPane1.setViewportView(jTable1);

        filterText.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtrar"));
        filterText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterTextActionPerformed(evt);
            }
        });
        filterText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filterTextKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(filterText, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                        .addGap(13, 13, 13))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(filterText, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 774, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 500));

        nameText.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        surnameText.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));

        homeText.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        idGroup1.add(dni);
        dni.setText("DNI");

        idGroup1.add(Lc);
        Lc.setText("LC");

        idGroup1.add(Le);
        Le.setText("LE");

        idGroup1.add(Ci);
        Ci.setText("CI");

        idText.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento"));

        email1Text.setBorder(javax.swing.BorderFactory.createTitledBorder("Email 1"));

        commentText.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario de disponibilidad"));

        movil2Text.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular 2"));

        email2Text.setBorder(javax.swing.BorderFactory.createTitledBorder("Email 2"));

        movil1Text.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular 1"));

        locationText.setBorder(javax.swing.BorderFactory.createTitledBorder("Localidad"));

        phoneText.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono"));

        neighborhoodText.setBorder(javax.swing.BorderFactory.createTitledBorder("Barrio"));

        addButton.setText("Agregar");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel5.add(addButton);

        deleteButton.setText("Borrar");
        deleteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButtonMouseClicked(evt);
            }
        });
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel5.add(deleteButton);

        modifyButton.setText("Modificar");
        modifyButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modifyButtonMouseClicked(evt);
            }
        });
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });
        jPanel5.add(modifyButton);

        jLabel2.setText("Elija el tipo de documento:");

        jLabel3.setText("Estado Civil: ");

        maritalGroup2.add(soltero);
        soltero.setText("Soltero");

        maritalGroup2.add(casado);
        casado.setText("Casado");

        nacimiento.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Nacimiento"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(commentText, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                                    .addComponent(email1Text))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(casado, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                            .addComponent(soltero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(43, 43, 43))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(email2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(nameText)
                                .addGap(60, 60, 60)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(dni)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Lc)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Le)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Ci))
                                    .addComponent(surnameText, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(idText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                                                .addComponent(locationText, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(31, 31, 31)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(movil2Text, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(neighborhoodText, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(homeText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(movil1Text, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 55, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText)
                    .addComponent(surnameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dni)
                    .addComponent(jLabel2)
                    .addComponent(Lc)
                    .addComponent(Le)
                    .addComponent(Ci))
                .addGap(5, 5, 5)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(neighborhoodText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(phoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movil1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movil2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(commentText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(soltero))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(casado)))
                .addGap(148, 148, 148)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, java.awt.BorderLayout.EAST);

        jTabbedPane1.addTab("Ejercicio 1", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(1021, 1021));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel11, java.awt.BorderLayout.NORTH);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Tipo Documento", "Documento", "Domicilio", "Localidad", "Barrio", "Fecha de Nacimiento", "Telefono", "Celular 1", "Celular 2", "Email 1 ", "Email 2", "Horario de Disponibilidad", "Estado Civil", "Edad", "Razon Social"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setPreferredSize(new java.awt.Dimension(300, 300));
        jScrollPane3.setViewportView(jTable2);

        jPanel7.setPreferredSize(new java.awt.Dimension(500, 500));

        jButton4.setText("Asignar Habitacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Liberar Habitacion");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addGap(84, 84, 84))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jCheckBox1.setText("Si");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Habitacion en servicio?");

        jPanel12.setPreferredSize(new java.awt.Dimension(1000, 500));

        nameText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre"));

        surnameText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Apellido"));

        homeText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Domicilio"));

        id2.add(dniRadioButton1);
        dniRadioButton1.setText("DNI");

        id2.add(lcRadioButton1);
        lcRadioButton1.setText("LC");

        id2.add(leRadioButton1);
        leRadioButton1.setText("LE");

        id2.add(ciRadioButton1);
        ciRadioButton1.setText("CI");

        idText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Documento"));

        email1Text1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email 1"));

        commentText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Horario de disponibilidad"));

        movil2Text1.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular 2"));

        email2Text1.setBorder(javax.swing.BorderFactory.createTitledBorder("Email 2"));
        email2Text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email2Text1ActionPerformed(evt);
            }
        });

        movil1Text1.setBorder(javax.swing.BorderFactory.createTitledBorder("Celular 1"));

        locationText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Localidad"));

        dateBirthText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha de Nacimiento"));

        phoneText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Teléfono"));

        neighborhoodText1.setBorder(javax.swing.BorderFactory.createTitledBorder("Barrio"));

        jLabel4.setText("Elija el tipo de documento:");

        jLabel5.setText("Estado Civil: ");

        marital2.add(jRadioButton3);
        jRadioButton3.setText("Soltero");

        marital2.add(jRadioButton4);
        jRadioButton4.setText("Casado");

        bussinesNameText.setBorder(javax.swing.BorderFactory.createTitledBorder("Razón Social"));

        ageText.setBorder(javax.swing.BorderFactory.createTitledBorder("Edad"));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(email2Text1, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                            .addComponent(phoneText1)
                            .addComponent(homeText1)
                            .addComponent(nameText1))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(surnameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(locationText1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(commentText1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movil1Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel12Layout.createSequentialGroup()
                                    .addComponent(dniRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lcRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(leRadioButton1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ciRadioButton1)))
                            .addGap(49, 49, 49)
                            .addComponent(idText1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel12Layout.createSequentialGroup()
                            .addComponent(neighborhoodText1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateBirthText1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movil2Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bussinesNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email1Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameText1)
                            .addComponent(surnameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(neighborhoodText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateBirthText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(phoneText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movil1Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movil2Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(email1Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email2Text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(commentText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bussinesNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dniRadioButton1)
                                    .addComponent(lcRadioButton1)
                                    .addComponent(leRadioButton1)
                                    .addComponent(ciRadioButton1))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jRadioButton3)))
                .addGap(311, 311, 311))
        );

        jPanel9.setAlignmentX(10.0F);
        jPanel9.setAlignmentY(10.0F);
        jPanel9.setPreferredSize(new java.awt.Dimension(500, 50));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Habitacion 1", "Habitacion 2", "Habitacion 3", "Habitacion 4", "Habitacion 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1243, 1243, 1243))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 1231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(jCheckBox1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel10, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Ejercicio 2", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void email2Text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email2Text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email2Text1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void filterTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterTextActionPerformed
        
    }//GEN-LAST:event_filterTextActionPerformed

    private void filterTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filterTextKeyReleased
        try{
            //hace que el filtro tenga el formato de la primer letra en mayuscula y el resto en minuscula.
            String correctFilter = (filterText.getText().trim().substring(0, 1).toUpperCase() + filterText.getText().trim().substring(1).toLowerCase());
            elQueOrdena.setRowFilter(RowFilter.regexFilter(correctFilter, 0));
            
        }
        catch(StringIndexOutOfBoundsException e){
            //agarra la excepcion de cuando el campo de texto queda vacio, y manda una alerta.
            
            elQueOrdena.setRowFilter(RowFilter.regexFilter("(?i)"+filterText.getText().trim(), 0));
            
        }
    }//GEN-LAST:event_filterTextKeyReleased

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        
            
        
    
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
      
    }//GEN-LAST:event_addButtonActionPerformed

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
            String name = nameText.getText().trim();
            String surname = surnameText.getText().trim();
            String typeId = "";
            String id = idText.getText().trim();
            String location = locationText.getText().trim();
            String home = homeText.getText().trim();
            String neighborhood = neighborhoodText.getText().trim();
            String date = sdf.format(nacimiento.getDate());
            String phone = phoneText.getText().trim();
            String movil1 = movil1Text.getText().trim();
            String movil2 = movil2Text.getText().trim();
            String email1 = email1Text.getText().trim();
            String email2 = email2Text.getText().trim();
            String maritalStatus = "";
            String comment= commentText.getText().trim();
            String correctName = "";
            String correctSurname = "";
            Integer correctMovil1 = 0;
            Integer correctMovil2 = 0;
            String correctLocation = "";
            String correctEmail1 = "";
            String correctEmail2 = "";
            String correctNeigh = "";
            Integer correctPhone = 0;
            
            if (dni.isSelected()){
                typeId = "DNI";
            }
            if(Lc.isSelected()){
                typeId = "LC";
            }
            if (Le.isSelected()){
                typeId = "LE";
            }
            else{
                typeId = "CI";
            }
            
            if (soltero.isSelected()){
                maritalStatus = "Soltero";
            }
            if (casado.isSelected()){
                maritalStatus = "Casado";
            }
            
            // se comprueba si los datos con string cumplen con la condicion de solo tener letras.
            if (isAlpha(name)) {
                //hace que el nombre tenga el formato de la primer letra en mayuscula y el resto en minuscula.
                correctName = (name.substring(0, 1).toUpperCase() + name.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el nombre solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                nameText.setText("");
                nameText.requestFocus();
                return;
            }
            
            if (isAlpha(surname)) {
                correctSurname = (surname.substring(0, 1).toUpperCase() + surname.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar la raza solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                surnameText.setText("");
                surnameText.requestFocus();
            }
            if (isAlpha(location)) {
                correctLocation = (location.substring(0, 1).toUpperCase() + location.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar la locacion solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                locationText.setText("");
                locationText.requestFocus();
            }
            if (isAlpha(neighborhood)) {
                //hace que la raza tenga el formato de la primer letra en mayuscula y el resto en minuscula.
               correctNeigh = (neighborhood.substring(0, 1).toUpperCase() + neighborhood.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el barrio solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                neighborhoodText.setText("");
                neighborhoodText.requestFocus();
            }

            // se comprueba si datos con numeros cumplen con la condicion de solo tener números.
            try {
                phone.chars().allMatch(Character::isDigit);
                //se transforma el dato de string a int.
                correctPhone = Integer.parseInt(phoneText.getText().trim());

            } catch (NumberFormatException e) {
               
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el telefono solo se permiten números!", "Atencion", JOptionPane.WARNING_MESSAGE);
                phoneText.setText("");
                phoneText.requestFocus();
            }

            try {
                movil1.chars().allMatch(Character::isDigit);
                //se transforma el dato de string a int.
                correctMovil1 = Integer.parseInt(movil1Text.getText().trim());

            } catch (NumberFormatException e) {
               
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el celular solo se permiten números!", "Atencion", JOptionPane.WARNING_MESSAGE);
                movil1Text.setText("");
                movil1Text.requestFocus();
            }
            try {
                movil2.chars().allMatch(Character::isDigit);
                //se transforma el dato de string a int.
                correctMovil2 = Integer.parseInt(movil1Text.getText().trim());

            } catch (NumberFormatException e) {
               
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el celular solo se permiten números!", "Atencion", JOptionPane.WARNING_MESSAGE);
                movil2Text.setText("");
                movil2Text.requestFocus();
            }
            
            // Patrón para validar el email
            if (isEmail(email1)) {
                correctEmail1 = email1;
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Email incorrecto, ingrese un email válido!", "Atencion", JOptionPane.WARNING_MESSAGE);
                email1Text.setText("");
                email1Text.requestFocus();
            }
            
             if (isEmail(email2)) {
                correctEmail2 = email2;
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Email incorrecto, ingrese un email válido!", "Atencion", JOptionPane.WARNING_MESSAGE);
                email2Text.setText("");
                email2Text.requestFocus();
            }
            if (!correctName.isEmpty() && !correctSurname.isEmpty()&& correctMovil1 > 0 && !correctEmail1.isEmpty()) {
            //agrega los datos a la tabla
            Object[] rowData = {correctName,correctSurname,typeId,id,correctLocation,home,correctNeigh,date,phone,correctMovil1,correctMovil2,
                    
            correctEmail1,correctEmail2,comment,maritalStatus};
            modelo.addRow(rowData);
            
            Clean();
            }
              
    }//GEN-LAST:event_addButtonMouseClicked

    private void modifyButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modifyButtonMouseClicked
        int index = jTable1.getSelectedRow();
        if (index < 0) {
            JOptionPane.showMessageDialog(null, "Para poder modificar un registro, debe seleccionarlo!", "Atencion", JOptionPane.WARNING_MESSAGE);
            //JOptionPane.showMessageDialog(jPanel4, "Para poder modificar un registro, debe seleccionarlo!", "Atencion", JOptionPane.WARNING_MESSAGE);
        } else {
            
            String name = nameText.getText().trim();
            String surname = surnameText.getText().trim();
            String typeId = "";
            String id = idText.getText().trim();
            String location = locationText.getText().trim();
            String home = homeText.getText().trim();
            String neighborhood = neighborhoodText.getText().trim();
            String date = sdf.format(nacimiento.getDate());
            String phone = phoneText.getText().trim();
            String movil1 = movil1Text.getText().trim();
            String movil2 = movil2Text.getText().trim();
            String email1 = email1Text.getText().trim();
            String email2 = email2Text.getText().trim();
            String maritalStatus = "";
            String comment= commentText.getText().trim();
            String correctName = "";
            String correctSurname = "";
            Integer correctMovil1 = 0;
            Integer correctMovil2 = 0;
            String correctLocation = "";
            String correctEmail1 = "";
            String correctEmail2 = "";
            String correctNeigh = "";
            Integer correctPhone = 0;
            
            if (dni.isSelected()){
                typeId = "DNI";
            }
            if(Lc.isSelected()){
                typeId = "LC";
            }
            if (Le.isSelected()){
                typeId = "LE";
            }
            else{
                typeId = "CI";
            }
            
            if (soltero.isSelected()){
                maritalStatus = "Soltero";
            }
            if (casado.isSelected()){
                maritalStatus = "Casado";
            }
            
            // se comprueba si los datos con string cumplen con la condicion de solo tener letras.
            if (isAlpha(name)) {
                //hace que el nombre tenga el formato de la primer letra en mayuscula y el resto en minuscula.
                correctName = (name.substring(0, 1).toUpperCase() + name.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el nombre solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                nameText.setText("");
                nameText.requestFocus();
                return;
            }
            
            if (isAlpha(surname)) {
                correctSurname = (surname.substring(0, 1).toUpperCase() + surname.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar la raza solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                surnameText.setText("");
                surnameText.requestFocus();
            }
            if (isAlpha(location)) {
                correctLocation = (location.substring(0, 1).toUpperCase() + location.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar la locacion solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                locationText.setText("");
                locationText.requestFocus();
            }
            if (isAlpha(neighborhood)) {
                //hace que la raza tenga el formato de la primer letra en mayuscula y el resto en minuscula.
                correctNeigh = (neighborhood.substring(0, 1).toUpperCase() + neighborhood.substring(1).toLowerCase());
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el barrio solo se permiten letras!", "Atencion", JOptionPane.WARNING_MESSAGE);
                neighborhoodText.setText("");
                neighborhoodText.requestFocus();
            }

            // se comprueba si datos con numeros cumplen con la condicion de solo tener números.
            try {
                phone.chars().allMatch(Character::isDigit);
                //se transforma el dato de string a int.
                correctPhone = Integer.parseInt(phoneText.getText().trim());

            } catch (NumberFormatException e) {
               
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el telefono solo se permiten números!", "Atencion", JOptionPane.WARNING_MESSAGE);
                phoneText.setText("");
                phoneText.requestFocus();
            }

            try {
                movil1.chars().allMatch(Character::isDigit);
                //se transforma el dato de string a int.
                correctMovil1 = Integer.parseInt(movil1Text.getText().trim());

            } catch (NumberFormatException e) {
               
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el celular solo se permiten números!", "Atencion", JOptionPane.WARNING_MESSAGE);
                movil1Text.setText("");
                movil1Text.requestFocus();
            }
            try {
                movil2.chars().allMatch(Character::isDigit);
                //se transforma el dato de string a int.
                correctMovil2 = Integer.parseInt(movil1Text.getText().trim());

            } catch (NumberFormatException e) {
               
                JOptionPane.showMessageDialog(modifyButton, "Para ingresar el celular solo se permiten números!", "Atencion", JOptionPane.WARNING_MESSAGE);
                movil2Text.setText("");
                movil2Text.requestFocus();
            }
            
            // Patrón para validar el email
            if (isEmail(email1)) {
                correctEmail1 = email1;
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Email incorrecto, ingrese un email válido!", "Atencion", JOptionPane.WARNING_MESSAGE);
                email1Text.setText("");
                email1Text.requestFocus();
            }
            
             if (isEmail(email2)) {
                correctEmail2 = email2;
            } else {
                JOptionPane.showMessageDialog(modifyButton, "Email incorrecto, ingrese un email válido!", "Atencion", JOptionPane.WARNING_MESSAGE);
                email2Text.setText("");
                email2Text.requestFocus();
            }
    
            /*si cumple con las condiciones y dejará vacios los campos de datos*/
            if (!correctName.isEmpty() && !correctSurname.isEmpty()&& correctMovil1 > 0 && !correctEmail1.isEmpty()){

                /*modelo.setValueAt(correctName, index, 0);
                modelo.setValueAt(correctSurname, index, 1);
                modelo.setValueAt(, index, 2);
                modelo.setValueAt(correctBreed, index, 3);

                Clean();
                nameText.requestFocus();
                */
                //es para que deje de estar seleccionada la fila
                jTable1.getSelectionModel().clearSelection();
    }//GEN-LAST:event_modifyButtonMouseClicked
        }
    }
    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButtonMouseClicked
        try {
            //borra la fila seleccionada
            int index = jTable1.getSelectedRow();
            modelo.removeRow(index);

            Clean();
            nameText.requestFocus();
        } catch (ArrayIndexOutOfBoundsException e) {
            //alerta para cuando no seleccionan una fila
            JOptionPane.showMessageDialog(null, "Para poder borrar un registro, debe seleccionarlo!", "Atencion", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonMouseClicked
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ci;
    private javax.swing.JRadioButton Lc;
    private javax.swing.JRadioButton Le;
    private javax.swing.JButton addButton;
    private javax.swing.JTextField ageText;
    private javax.swing.JTextField bussinesNameText;
    private javax.swing.JRadioButton casado;
    private javax.swing.JRadioButton ciRadioButton1;
    private javax.swing.JTextField commentText;
    private javax.swing.JTextField commentText1;
    private javax.swing.JTextField dateBirthText1;
    private javax.swing.JButton deleteButton;
    private javax.swing.JRadioButton dni;
    private javax.swing.JRadioButton dniRadioButton1;
    private javax.swing.JTextField email1Text;
    private javax.swing.JTextField email1Text1;
    private javax.swing.JTextField email2Text;
    private javax.swing.JTextField email2Text1;
    private javax.swing.JTextField filterText;
    private javax.swing.JTextField homeText;
    private javax.swing.JTextField homeText1;
    private javax.swing.ButtonGroup id2;
    private javax.swing.ButtonGroup idGroup1;
    private javax.swing.JTextField idText;
    private javax.swing.JTextField idText1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton lcRadioButton1;
    private javax.swing.JRadioButton leRadioButton1;
    private javax.swing.JTextField locationText;
    private javax.swing.JTextField locationText1;
    private javax.swing.ButtonGroup marital2;
    private javax.swing.ButtonGroup maritalGroup2;
    private javax.swing.JButton modifyButton;
    private javax.swing.JTextField movil1Text;
    private javax.swing.JTextField movil1Text1;
    private javax.swing.JTextField movil2Text;
    private javax.swing.JTextField movil2Text1;
    private com.toedter.calendar.JDateChooser nacimiento;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JTextField neighborhoodText;
    private javax.swing.JTextField neighborhoodText1;
    private javax.swing.JTextField phoneText;
    private javax.swing.JTextField phoneText1;
    private javax.swing.JRadioButton soltero;
    private javax.swing.JTextField surnameText;
    private javax.swing.JTextField surnameText1;
    // End of variables declaration//GEN-END:variables
}
